services:
  eballshop:
    build:
      context: .
      dockerfile: EBallShop/Dockerfile
    ports:
      - "5001:8080"
      - "5002:8081"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ./data:/app/data

  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "5003:8080"
      - "5004:8081"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ./data:/app/data

  shoppingcart:
    build:
      context: .
      dockerfile: ShoppingCart/Dockerfile
    ports:
      - "5005:8080"
      - "5006:8081"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ./data:/app/data

networks:
  backend:
    driver: bridge
